plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.smartsolarmicrogrid'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.smartsolarmicrogrid"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.activity.ktx

    // Network (Retrofit & Gson)
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.gson

    // Google Play Services Maps & Location
    implementation libs.play.services.maps
    implementation libs.play.services.location

    // Free OpenSource OpenStreetMap (osmdroid)
    implementation libs.osmdroid.android

    // ZXing for QR Code generation and camera scanning
    implementation libs.zxing.android.embedded
    implementation libs.zxing.core

    // Testing
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
